site_name: SeaTable Scripts Programming Manual
site_author: seatable
docs_dir: ./manual
site_url: https://seatable.github.io/seatable-scripts/


repo_name: seatable/seatable-scripts
repo_url: https://github.com/seatable/seatable-scripts/
edit_uri: edit/master/manual/

copyright: Copyright &copy; 2020 seatable

theme:
  name: material
  # icon:
  logo: assets/logo32_32.png
  favicon: assets/seatable-favicon.ico
  # features:
    # - tabs
  palette:
    primary: deep orange
    accent:

plugins:
  - search # necessary for search to work
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seatable/seatable-scripts/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"


# Page tree
nav:
  - Home: README.md
  - Data structure: data-structure.md
  - JavaScript:
    - Introduction: javascript/README.md
    - Base: javascript/base.md
    - Output: javascript/output.md
    - Utils: javascript/utils.md
    - Context: javascript/context.md
  - Python:
    - Introduction: python/README.md
    - Base: python/base.md
    - QuerySet: python/queryset.md
    - Rows: python/rows.md
    - Links: python/links.md
    - Columns: python/columns.md
    - Files: python/files.md
    - Account: python/account.md
    - Constants: python/constants.md
    - Context: python/context.md
    - Libraries supported in cloud environment: python/libs.md
    - Query Statements: python/query-sentences.md
